site_name: SQLA Wrapper
site_description: A friendly wrapper for modern SQLAlchemy and Alembic
site_url: https://sqla-wrapper.scaletti.dev
repo_url: https://github.com/jpsca/sqla-wrapper
repo_name: jpsca/sqla-wrapper
copyright: Copyright &copy; 2013 Juan-Pablo Scaletti

nav:
  - Home: index.md
  - SQLAlchemy:
    - sqlalchemy-wrapper.md
    - working-with-the-session.md
    - testing-with-a-real-database.md
  - Alembic:
    - alembic-wrapper.md
  - how-to.md
  - API:
    - api/sqlalchemy-wrapper-class.md
    - api/session-class.md
    - api/testtransaction-class.md
    - api/alembic-wrapper-class.md

theme:
  name: material
  logo: assets/img/logo.svg
  favicon: assets/img/favicon.svg
  font:
    text: Convergence
    code: Roboto Mono
  custom_dir: overrides
  language: en
  features:
    - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highligh
  icon:
    repo: material/github
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: red
    accent: pink
    toggle:
      icon: octicons/sun-16
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: pink
    toggle:
      icon: octicons/moon-16
      name: Switch to light mode

extra_css:
  - assets/css/highlight.css
  # - assets/css/termynal.css
  - assets/css/common.css
# extra_javascript:
  # - assets/js/termynal.js
edit_uri: ""
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: false
            show_source: false


markdown_extensions:
  - admonition
  - attr_list
  - smarty
  - tables
  - toc:
      permalink: "#"
      toc_depth: 4
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
